name: boring_app
description: A new Flutter project.
 
publish_to: 'none' 

 
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
 
dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.1.1
  http: ^0.13.5
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  intl: ^0.18.0
  flutter_launcher_icons: ^0.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0
  isar_generator: ^3.0.5
  build_runner: ^2.3.3
 
flutter:
 
  uses-material-design: true

  assets:
    - assets/img/bored_icon.png
 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/bored_icon.png"
  min_sdk_android: 21